### ISSUE TITLE
Add support for publishing battery charge level

### ISSUE THREAD

**Issue by synaptiko** [bigclownlabs/bcf-sdk#162]
Because you offer two various battery modules I think it would be more useful to sent battery charge level instead of voltage. The reason is that if you save data from sensors into e.g. InfluxDB and you want to graph the charge level you have to know the "maximum" voltage for each sensor which is not easy to do.

Here's what I've implemented for myself for now: https://github.com/synaptiko/bigclown-nodes-firmware/blob/master/apps/climate-monitor/application.c#L34-L44

**Comment by hubpav** [comment]
Hi! We are not hearing this suggestion for the first time and I agree that most users are concerned about the relative charge level rather than the actual voltage. However, we have a good reason to believe that having this baked in the firmware is a wrong place, because you may use different types of batteries (Alkaline, Lithium, NiMH) - all of them having different starting voltage and different discharge curves. But I may have a solution to this problem: What about if we had small Python agent listening to MQTT topics about the battery voltage and translating them (publishing) to the real charge level based on configuration. You could have key-value settings for your radio node IDs where the value would be a type of battery and the agent would have returned accurate charge level. What do you think? Thanks!

**Comment by synaptiko** [comment]
Hello. Yes, I didn't realize that you can use different types of batteries with different characteristics. Now I have to agree with you that the firmware is not the right place for this.

I like your idea about the MQTT agent, I had a similar idea yesterday because I was thinking about how to get rid of this part of the script: https://github.com/synaptiko/bigclown-influxdb-grafana-installation/blob/master/bc-mqtt-to-influxdb.py#L80.

I think the agent could be more generic, maybe it could be "pluggable". With the default "voltage-to-charge-level" plugin.

**Comment by mkyral** [comment]
@hubpav I already did it. 

https://gist.github.com/mkyral/ba1b0eee1e76778c7a27b9650e9375e6

Still unfinished, only linear curve, missing config file support. But currently have not much time for BC development (and I need at least one more core module for develoment ;-) )
